### PR TITLE
sendTo uses shared connection: making sure messages get delivered to the correct rooms. 

### LINKED ISSUE #25: Wrong topicIDs when sending a direct message
As I started debugging what's causing https://github.com/orbitdb/orbit-db/issues/258, I found out that when sending direct messages, we **sometimes** have the wrong topicID in our topicIDs array. 

If I'm not mistaken, the peer connection is shared between rooms (topics), so when we send a direct message to the peer, it might end up getting handled in a different room instance. This is, I believe, because of the `_handleDirectConnection()` [pulls directly](https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L135) from the (shared-between-rooms) connection and as such, the handler being used can be the one created in room A while the message was sent via room B. So essentially, when we set `topicCIDs: [ this._topic ]`, *this* is not actually tied to the topic.

I'm not sure how we should fix this. It feels to me as it is today, it's breaking the *room* abstraction (a direct message sent from one room can "appear" in another), but then again, sending a direct message to a peer on the abstraction level doesn't necessarily need to be tied to a particular room. One solution would be to change the `sendTo()` method so that it creates a proper PubSub message [like we do on the receiving end](https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/master/src/index.js#L145), that way we can tie the room (topic) ID to the direct message. 

The question is, do we want that? Do we want the direct messages be per-room, or do we want them to be per-user/connection?

Any thoughts @pgte?

### PR DESCRIPTION
**Pull request by pgte**
Should fix #25

### CODE REVIEW

**Comment by pgte** [comment]
Very much inspired by @haadcode [own fix](https://github.com/haadcode/ipfs-pubsub-room/blob/fix/direct-messges-in-room/src/index.js#L154). Thanks!

**Comment by pgte** [comment]
Also, fixes error masking that was coming out of the connection pull stream.
https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/26/files#diff-1fdf421c05c1140f6d71444ea2b27638R185

**Comment by haadcode** [comment]
Awesome! Thanks for fixing it. Out of curiosity, why didn't you go with the fix you proposed?

**Comment by pgte** [comment]
I think I did. [Here](https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/26/files#diff-1fdf421c05c1140f6d71444ea2b27638R174) I'm filtering the incoming messages based on topic. Isn't this what you were expecting?

**Pull request merged**
