### PR TITLE
Update to support libp2p >=0.29.0

### PR DESCRIPTION
**Pull request by HexaField**
Breaking changes to the way PeerID and the move from Buffers to Uint8Arrays meant this package is no longer compatible with libp2p >=v0.29.0

This PR updates ipfs-pubsub-room to support the latest libp2p, though does not include a publish-ready status.

### CODE REVIEW

**Comment by jacobfriedman** [comment]
Bump

**Comment by straiforos** [comment]
Happy new year!

The commit messages are not formatted according to Commit Lint library standards. I am working to update this on your behalf. Or if you could update to state chore: <message>

**Review by straiforos — APPROVED** [review]
Looks great, unfortunately the commit messages are not correct.  The work passes so I am going to push this through and see if the community hates me or not. :) I want this fix in my work and would hate to redo and take credit for this amazing work. Well done @HexaField! Next time please update the commit messages to state commit lint message statuses. https://github.com/conventional-changelog/commitlint

**Comment by HexaField** [comment]
You may want to check out this. Since this repo has had no action in a year I have updated this code further elsewhere. It has not been released. I can create a PR with these updates soon.

https://github.com/HexaField/js-libp2p-pubsub-room

**Pull request closed without merging**
