### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by josselinchevalay**
i found this event in index.js. i think can check if node are correctly subscribe to channel before to use `broadcast` and `sendTo`.

### CODE REVIEW

**Comment by josselinchevalay** [comment]
@pgte

**Comment by josselinchevalay** [comment]
@diasdavid

**Comment by pgte** [comment]
@josselinchevalay thank you!

Looks great, but I think the event description may be a bit deceiving: the event is emitted once the channel is subscribed in IPFS pubsub. The difference is that a subscription is a local operation, it implies no communication has happened with other nodes.

**Comment by josselinchevalay** [comment]
so this event is thow when your room is created on IPFS daemon (locally)?

**Comment by pgte** [comment]
It's emitted once the call to ipfs.pubsub.subscribe(topic, cb) calls back.

**Comment by josselinchevalay** [comment]
```
# room.on('subscribed', () => {})
Once your program has subscribe the topic on ipfs pubsub. 
```` 

What do you think about that ?

**Comment by pgte** [comment]
Sounds good!

**Comment by diasdavid** [comment]
thanks @josselinchevalay :)

**Pull request merged**
